# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hranilishe.filesystem
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lotok.Category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('resource', models.FileField(max_length=256, storage=hranilishe.filesystem.HashedFileSystemStorage(), upload_to=hranilishe.filesystem.upload_by_hash, verbose_name='model')),
                ('size', models.PositiveIntegerField(default=0, help_text='The size of the uploaded detail.')),
                ('is_compressed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('md5sum', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Do not show this product')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotok.Category')),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='title')),
                ('value', models.CharField(max_length=128, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotok.Product')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ('key',),
            },
        ),
    ]
